language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "9"
  - "8"
  - "6"
sudo: required
before_script:
  - npm prune
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js