language: node_js
cache:
  directories:
  - node_modules
node_js:
- '9'
- '8'
sudo: required
after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true